baseURL: https://adrienchinour.me
languageCode: fr-FR
defaultContentLanguage: fr
title: Adrien Chinour
theme: cupper-hugo-theme
enableGitInfo: true

taxonomies:
  tag: tag

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Blog d'un _développeur du Web_.
  homeMetaContent: Blog d'un développeur du Web. Adrien Chinour, développeur PHP.
  footer: "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/). _PS: Longue vie au PHP_."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  katex: false

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: À Propos
      url: /about/
      weight: 3

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
